# Generated by Django 5.2.8 on 2025-11-11 09:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Numéro de téléphone')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Téléphone vérifié')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('two_factor_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('newsletter_subscribed', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_location', models.CharField(blank=True, max_length=200, null=True)),
                ('account_locked', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de vérification',
                'verbose_name_plural': 'Tokens de vérification',
            },
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=300)),
                ('code_postal', models.CharField(default='31000', max_length=5)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (loyer mensuel)')),
                ('surface', models.FloatField(verbose_name='Surface (m²)')),
                ('description', models.TextField(blank=True, null=True)),
                ('type_logement', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio'), ('chambre', 'Chambre'), ('autre', 'Autre')], default='appartement', max_length=20)),
                ('chambres', models.IntegerField(default=1)),
                ('etage', models.CharField(choices=[('rdc', 'Rez-de-chaussée'), ('etage', 'Étage'), ('dernier', 'Dernier étage')], default='etage', max_length=20)),
                ('date_mutation', models.DateField(blank=True, null=True, verbose_name='Date de vente')),
                ('valeur_fonciere', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de vente')),
                ('id_parcelle', models.CharField(blank=True, max_length=20, null=True, verbose_name='Référence cadastrale')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reclame', 'Réclamé (en attente)'), ('verifie', 'Vérifié (propriétaire confirmé)')], default='disponible', max_length=20)),
                ('note_moyenne', models.FloatField(default=0, verbose_name='Note moyenne')),
                ('nombre_avis', models.IntegerField(default=0, verbose_name="Nombre d'avis")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens_possedes', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire vérifié')),
            ],
            options={
                'verbose_name': 'Logement',
                'verbose_name_plural': 'Logements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('note_personnelle', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_favoris', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_utilisateurs', to='core.logement')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='AvisLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1 à 5 étoiles)')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'avis")),
                ('commentaire', models.TextField(verbose_name='Commentaire détaillé')),
                ('note_proprete', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_equipements', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_localisation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_bailleur', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('verifie', models.BooleanField(default=False, verbose_name='Vérifié (vrai locataire)')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/locataires/', verbose_name='Justificatif (quittance de loyer)')),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_avis', to=settings.AUTH_USER_MODEL)),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_verifies', to=settings.AUTH_USER_MODEL)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='core.logement')),
            ],
            options={
                'verbose_name': 'Avis locataire',
                'verbose_name_plural': 'Avis locataires',
                'ordering': ['-date_avis'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('suspicious', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token réinitialisation',
                'verbose_name_plural': 'Tokens réinitialisation',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bio_longue', models.TextField(blank=True, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_etendu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil étendu',
                'verbose_name_plural': 'Profils étendus',
            },
        ),
        migrations.CreateModel(
            name='ReclamationProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificatif', models.FileField(upload_to='justificatifs/proprietaires/', verbose_name='Justificatif (taxe foncière, titre de propriété)')),
                ('message', models.TextField(verbose_name='Message explicatif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire administrateur')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.logement')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_reclamations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réclamation propriétaire',
                'verbose_name_plural': 'Réclamations propriétaires',
                'ordering': ['-date_reclamation'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_name', models.CharField(max_length=200)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session active',
                'verbose_name_plural': 'Sessions actives',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['code_postal', 'type_logement'], name='core_logeme_code_po_3eeb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['prix', 'surface'], name='core_logeme_prix_8bd1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['note_moyenne'], name='core_logeme_note_mo_e251cf_idx'),
        ),
        migrations.AddIndex(
            model_name='favori',
            index=models.Index(fields=['utilisateur', 'date_ajout'], name='favori_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('utilisateur', 'logement')},
        ),
        migrations.AlterUniqueTogether(
            name='avislogement',
            unique_together={('logement', 'locataire')},
        ),
        migrations.AlterUniqueTogether(
            name='reclamationproprietaire',
            unique_together={('logement', 'utilisateur', 'statut')},
        ),
    ]
