# Generated by Django 5.2.8 on 2025-11-07 12:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1 à 5 étoiles)')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'avis")),
                ('commentaire', models.TextField(verbose_name='Commentaire détaillé')),
                ('note_proprete', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_equipements', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_localisation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_bailleur', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('verifie', models.BooleanField(default=False, verbose_name='Vérifié (vrai locataire)')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/locataires/', verbose_name='Justificatif (quittance de loyer)')),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Avis locataire',
                'verbose_name_plural': 'Avis locataires',
                'ordering': ['-date_avis'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificatif', models.FileField(upload_to='justificatifs/proprietaires/', verbose_name='Justificatif (taxe foncière, titre de propriété)')),
                ('message', models.TextField(verbose_name='Message explicatif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire administrateur')),
            ],
            options={
                'verbose_name': 'Réclamation propriétaire',
                'verbose_name_plural': 'Réclamations propriétaires',
                'ordering': ['-date_reclamation'],
            },
        ),
        migrations.RenameIndex(
            model_name='favori',
            new_name='favori_user_idx',
            old_name='favori_user_date_idx',
        ),
        migrations.RemoveField(
            model_name='logement',
            name='note',
        ),
        migrations.AddField(
            model_name='logement',
            name='code_postal',
            field=models.CharField(default='31000', max_length=5),
        ),
        migrations.AddField(
            model_name='logement',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logement',
            name='date_mutation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de vente'),
        ),
        migrations.AddField(
            model_name='logement',
            name='id_parcelle',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Référence cadastrale'),
        ),
        migrations.AddField(
            model_name='logement',
            name='nombre_avis',
            field=models.IntegerField(default=0, verbose_name="Nombre d'avis"),
        ),
        migrations.AddField(
            model_name='logement',
            name='note_moyenne',
            field=models.FloatField(default=0, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='logement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens_possedes', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire vérifié'),
        ),
        migrations.AddField(
            model_name='logement',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reclame', 'Réclamé (en attente)'), ('verifie', 'Vérifié (propriétaire confirmé)')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='logement',
            name='valeur_fonciere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (loyer mensuel)'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='surface',
            field=models.FloatField(verbose_name='Surface (m²)'),
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['code_postal', 'type_logement'], name='core_logeme_code_po_3eeb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['prix', 'surface'], name='core_logeme_prix_8bd1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='logement',
            index=models.Index(fields=['note_moyenne'], name='core_logeme_note_mo_e251cf_idx'),
        ),
        migrations.AddField(
            model_name='avislogement',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_avis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avislogement',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='core.logement'),
        ),
        migrations.AddField(
            model_name='avislogement',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_verifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamationproprietaire',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.logement'),
        ),
        migrations.AddField(
            model_name='reclamationproprietaire',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamationproprietaire',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='avislogement',
            unique_together={('logement', 'locataire')},
        ),
        migrations.AlterUniqueTogether(
            name='reclamationproprietaire',
            unique_together={('logement', 'utilisateur', 'statut')},
        ),
    ]
