# Generated by Django 5.2.8 on 2025-11-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements/%Y/%m/', verbose_name='Image')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name="Titre de l'image")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_principale', models.BooleanField(default=False, verbose_name='Image principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.logement', verbose_name='Logement')),
            ],
            options={
                'verbose_name': 'Image logement',
                'verbose_name_plural': 'Images logement',
                'ordering': ['ordre', '-est_principale', '-date_ajout'],
                'indexes': [models.Index(fields=['logement', 'ordre'], name='core_imagel_logemen_4fae22_idx')],
            },
        ),
    ]
