# Generated by Django 5.2.7 on 2025-11-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_badge_magiclinktoken_twofactorbackupcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adresse_complete',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='afficher_derniere_visite',
            field=models.BooleanField(default=False, verbose_name='Afficher dernière visite'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='afficher_statut_online',
            field=models.BooleanField(default=True, verbose_name='Afficher statut en ligne'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_professionnel',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email professionnel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employeur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Employeur'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='heures_disponibilite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Heures de disponibilité'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_verified',
            field=models.BooleanField(default=False, verbose_name='Identité vérifiée'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locataire',
            field=models.BooleanField(default=True, verbose_name='Est locataire'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_professionnel',
            field=models.BooleanField(default=False, verbose_name='Propriétaire professionnel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_proprietaire',
            field=models.BooleanField(default=False, verbose_name='Est propriétaire'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière activité'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profil_public',
            field=models.BooleanField(default=True, verbose_name='Profil public'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='proprietaire_verified',
            field=models.BooleanField(default=False, verbose_name='Propriétaire vérifié'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='siren',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIREN'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='siret',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIRET'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='situation_professionnelle',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('etudiant', 'Étudiant'), ('retraite', 'Retraité'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Situation professionnelle'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
    ]
