# Generated by Django 5.2.7 on 2025-11-16 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_postcomment_commentlike_postdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi',
                'verbose_name_plural': 'Suivis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', '-created_at'], name='core_follow_followe_d0561e_idx'), models.Index(fields=['followed', '-created_at'], name='core_follow_followe_ece451_idx')],
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Raison')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocage',
                'verbose_name_plural': 'Blocages',
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('identity', 'Identité'), ('proprietaire', 'Propriétaire')], max_length=20, verbose_name='Type de vérification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut')),
                ('justificatif_propriete', models.FileField(blank=True, null=True, upload_to='verifications/proprietaires/%Y/%m/', verbose_name='Justificatif de propriété')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='verifications/identite/%Y/%m/', verbose_name="Pièce d'identité")),
                ('selfie_identite', models.ImageField(blank=True, null=True, upload_to='verifications/identite/selfies/%Y/%m/', verbose_name="Selfie avec pièce d'identité")),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message explicatif')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_requests', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de vérification',
                'verbose_name_plural': 'Demandes de vérification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'verification_type', 'status'], name='core_verifi_user_id_01d363_idx')],
            },
        ),
    ]
