# Generated by Django 5.2.7 on 2025-11-16 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_follow_userblock_verificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='Archivée')),
                ('favorited', models.BooleanField(default=False, verbose_name='Favoris')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statut de conversation',
                'verbose_name_plural': 'Statuts de conversation',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='messages/documents/%Y/%m/', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='message',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du document'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='Spam détecté'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_suspicious',
            field=models.BooleanField(default=False, verbose_name='Suspect'),
        ),
        migrations.AddField(
            model_name='message',
            name='spam_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Raison du spam'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='core_conver_updated_249e23_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='core_messag_convers_d2b392_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='core_messag_sender__43db24_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['read'], name='core_messag_read_14301c_idx'),
        ),
        migrations.AddField(
            model_name='conversationstatus',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.conversation'),
        ),
        migrations.AddField(
            model_name='conversationstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversationstatus',
            index=models.Index(fields=['user', 'archived'], name='core_conver_user_id_587358_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationstatus',
            index=models.Index(fields=['user', 'favorited'], name='core_conver_user_id_5ad608_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationstatus',
            unique_together={('conversation', 'user')},
        ),
    ]
