# Generated by Django 5.2.7 on 2025-11-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conversationstatus_message_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='message_email_notifications',
            field=models.BooleanField(default=True, verbose_name='Notifications email pour nouveaux messages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='message_push_notifications',
            field=models.BooleanField(default=True, verbose_name='Notifications push pour nouveaux messages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='who_can_message',
            field=models.CharField(choices=[('everyone', 'Tout le monde'), ('connections', 'Mes connexions uniquement'), ('verified', 'Utilisateurs vérifiés uniquement')], default='everyone', max_length=50, verbose_name="Qui peut m'envoyer un message"),
        ),
    ]
