# Generated by Django 5.2.7 on 2025-11-16 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_message_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_email_frequency',
            field=models.CharField(choices=[('immediate', 'Immédiate'), ('daily', 'Résumé quotidien'), ('weekly', 'Résumé hebdomadaire')], default='immediate', max_length=20, verbose_name='Fréquence des emails de notification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Préférences de notifications par type (email, push, in_app)', verbose_name='Paramètres de notifications'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name="De l'utilisateur"),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='related_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.postcomment'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='related_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.conversation'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='related_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.group'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='related_logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.logement'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.post'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="URL d'action"),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('connection_accepted', 'Connexion acceptée'), ('connection_request', 'Demande de connexion'), ('post_liked', 'Like sur un post'), ('post_commented', 'Commentaire sur un post'), ('comment_replied', 'Réponse à un commentaire'), ('post_mentioned', 'Mention dans un post'), ('comment_mentioned', 'Mention dans un commentaire'), ('new_message', 'Nouveau message'), ('group_invitation', 'Invitation à rejoindre un groupe'), ('group_post', 'Nouveau post dans un groupe'), ('property_updated', "Mise à jour d'un logement favori"), ('review_received', 'Avis reçu'), ('verification_approved', 'Vérification approuvée'), ('security', 'Sécurité'), ('system', 'Système')], default='system', max_length=30),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'notification_type', '-created_at'], name='core_userno_user_id_6ee56d_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['from_user', '-created_at'], name='core_userno_from_us_6f11dc_idx'),
        ),
    ]
