# Generated by Django 5.2.7 on 2025-16-01 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_group_members(apps, schema_editor):
    """Migrer les membres existants vers GroupMembership"""
    Group = apps.get_model('core', 'Group')
    GroupMembership = apps.get_model('core', 'GroupMembership')
    CustomUser = apps.get_model('core', 'CustomUser')
    
    # Pour chaque groupe, créer les membreships pour les membres existants
    for group in Group.objects.all():
        # Récupérer les membres via la table de jointure ManyToMany
        # Note: On doit utiliser la table temporaire car le champ members existe encore
        members = group.members.all()
        for member in members:
            GroupMembership.objects.get_or_create(
                group=group,
                user=member,
                defaults={
                    'role': 'member',
                    'status': 'accepted'
                }
            )
        
        # Traiter les admins aussi
        admins = group.admins.all()
        for admin in admins:
            membership, created = GroupMembership.objects.get_or_create(
                group=group,
                user=admin,
                defaults={
                    'role': 'admin',
                    'status': 'accepted'
                }
            )
            if not created:
                membership.role = 'admin'
                membership.status = 'accepted'
                membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customuser_notification_email_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('locataires', 'Locataires'), ('proprietaires', 'Propriétaires'), ('mixte', 'Mixte'), ('quartier', 'Quartier'), ('theme', 'Thème')], default='mixte', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='group',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description complète'),
        ),
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='group',
            name='require_approval',
            field=models.BooleanField(default=False, verbose_name="Demande d'approbation requise"),
        ),
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.TextField(blank=True, null=True, verbose_name='Règles du groupe'),
        ),
        migrations.AddField(
            model_name='group',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description courte'),
        ),
        # Créer GroupMembership d'abord
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('moderator', 'Modérateur'), ('admin', 'Administrateur')], default='member', max_length=20, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('banned', 'Banni')], default='pending', max_length=20, verbose_name='Statut')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de groupe',
                'verbose_name_plural': 'Membres de groupe',
                'ordering': ['-joined_at'],
            },
        ),
        # Migrer les données avant de modifier le champ members
        migrations.RunPython(migrate_group_members, migrations.RunPython.noop),
        # Maintenant modifier le champ members pour utiliser through
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='connect_groups', through='core.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['category', 'is_public'], name='core_group_categor_9357c2_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['ville', 'region'], name='core_group_ville_4c75ae_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['-created_at'], name='core_group_created_a9b9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'status'], name='core_groupm_group_i_618a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'status'], name='core_groupm_user_id_1d4f17_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'role'], name='core_groupm_group_i_f8f821_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
    ]
