# Generated by Django 5.2.7 on 2025-11-16 20:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_group_category_group_full_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Loyer mensuel')),
                ('charges_mensuelles', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charges mensuelles')),
                ('depot_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dépôt de garantie')),
                ('duree_mois', models.IntegerField(default=12, verbose_name='Durée (en mois)')),
                ('jour_paiement', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jour de paiement mensuel')),
                ('contrat_signe', models.FileField(blank=True, null=True, upload_to='baux/contrats/%Y/%m/', verbose_name='Contrat signé (PDF)')),
                ('etat_lieux_entree', models.FileField(blank=True, null=True, upload_to='baux/etat_lieux/%Y/%m/', verbose_name="État des lieux d'entrée (PDF)")),
                ('etat_lieux_sortie', models.FileField(blank=True, null=True, upload_to='baux/etat_lieux/%Y/%m/', verbose_name='État des lieux de sortie (PDF)')),
                ('assurance_habitation', models.FileField(blank=True, null=True, upload_to='baux/assurances/%Y/%m/', verbose_name='Assurance habitation')),
                ('assurance_date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance assurance")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('resiliation_en_cours', 'En cours de résiliation'), ('resilie', 'Résilié'), ('termine', 'Terminé')], default='actif', max_length=30, verbose_name='Statut')),
                ('clauses_importantes', models.TextField(blank=True, null=True, verbose_name='Clauses importantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baux_locataire', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baux', to='core.logement', verbose_name='Logement')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baux_proprietaire', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Baux',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemandeEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('plomberie', 'Plomberie'), ('electricite', 'Électricité'), ('chauffage', 'Chauffage'), ('climatisation', 'Climatisation'), ('peinture', 'Peinture'), ('vitrerie', 'Vitrerie'), ('porte_fenetre', 'Porte/Fenêtre'), ('isolation', 'Isolation'), ('sanitaire', 'Sanitaire'), ('autre', 'Autre')], max_length=30, verbose_name='Type de problème')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('urgence', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('faible', 'Faible')], default='normal', max_length=20, verbose_name='Urgence')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reponse_proprietaire', models.TextField(blank=True, null=True, verbose_name='Réponse du propriétaire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_entretien', to='core.bail', verbose_name='Bail')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_entretien', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_entretien_recues', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': "Demande d'entretien",
                'verbose_name_plural': "Demandes d'entretien",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeEntretienPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='baux/entretien/%Y/%m/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Légende')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='core.demandeentretien', verbose_name='Demande')),
            ],
            options={
                'verbose_name': "Photo demande d'entretien",
                'verbose_name_plural': "Photos demandes d'entretien",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='demandeentretien',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='demandes', to='core.demandeentretienphoto', verbose_name='Photos'),
        ),
        migrations.CreateModel(
            name='DocumentBail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('contrat', 'Contrat/Bail signé'), ('etat_lieux_entree', "État des lieux d'entrée"), ('etat_lieux_sortie', 'État des lieux de sortie'), ('quittance', 'Quittance de loyer'), ('assurance', 'Assurance habitation'), ('facture_charges', 'Facture de charges'), ('autre', 'Autre')], max_length=30, verbose_name='Type de document')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('document', models.FileField(upload_to='baux/documents/%Y/%m/', verbose_name='Document')),
                ('date_document', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.bail', verbose_name='Bail')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_bail_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document bail',
                'verbose_name_plural': 'Documents bail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant loyer')),
                ('montant_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant charges')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_retard', 'En retard'), ('en_attente', 'En attente')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('quittance', models.FileField(blank=True, null=True, upload_to='baux/quittances/%Y/%m/', verbose_name='Quittance (PDF)')),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.bail', verbose_name='Bail')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_loyer', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Paiement de loyer',
                'verbose_name_plural': 'Paiements de loyer',
                'ordering': ['-date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Resiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart_souhaitee', models.DateField(verbose_name='Date de départ souhaitée')),
                ('raison', models.TextField(blank=True, null=True, verbose_name='Raison (optionnelle)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reponse_proprietaire', models.TextField(blank=True, null=True, verbose_name='Réponse du propriétaire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('date_fin_effective', models.DateField(blank=True, null=True, verbose_name='Date de fin effective')),
                ('etat_lieux_sortie_fait', models.BooleanField(default=False, verbose_name='État des lieux de sortie effectué')),
                ('cles_restituées', models.BooleanField(default=False, verbose_name='Clés restituées')),
                ('depot_garantie_rendu', models.BooleanField(default=False, verbose_name='Dépôt de garantie rendu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resiliation', to='core.bail', verbose_name='Bail')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resiliations_locataire', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resiliations_proprietaire', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Résiliation',
                'verbose_name_plural': 'Résiliations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bail',
            index=models.Index(fields=['locataire', 'statut'], name='core_bail_locatai_b34522_idx'),
        ),
        migrations.AddIndex(
            model_name='bail',
            index=models.Index(fields=['proprietaire', 'statut'], name='core_bail_proprie_58bd41_idx'),
        ),
        migrations.AddIndex(
            model_name='bail',
            index=models.Index(fields=['date_debut', 'date_fin'], name='core_bail_date_de_d5ec7a_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeentretien',
            index=models.Index(fields=['bail', '-created_at'], name='core_demand_bail_id_6ce590_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeentretien',
            index=models.Index(fields=['locataire', 'statut'], name='core_demand_locatai_8286d0_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeentretien',
            index=models.Index(fields=['proprietaire', 'statut'], name='core_demand_proprie_f04936_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbail',
            index=models.Index(fields=['bail', 'type_document'], name='core_docume_bail_id_8e1cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbail',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='core_docume_uploade_1287de_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementloyer',
            index=models.Index(fields=['bail', '-date_echeance'], name='core_paieme_bail_id_1617f0_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementloyer',
            index=models.Index(fields=['locataire', 'statut'], name='core_paieme_locatai_556b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='resiliation',
            index=models.Index(fields=['locataire', 'statut'], name='core_resili_locatai_f4d2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='resiliation',
            index=models.Index(fields=['proprietaire', 'statut'], name='core_resili_proprie_b64312_idx'),
        ),
    ]
