# Generated by Django 5.2.7 on 2025-11-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bail_demandeentretien_demandeentretienphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='afficher_activite_recente',
            field=models.BooleanField(default=True, verbose_name='Afficher mon activité récente'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='afficher_logements_profil',
            field=models.BooleanField(default=True, verbose_name='Afficher mes logements sur mon profil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='connect_disabled',
            field=models.BooleanField(default=False, verbose_name='Profil Connect désactivé'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profil_visibility',
            field=models.CharField(choices=[('public', 'Public - Visible par tous'), ('connections', 'Connexions uniquement - Visible par mes connexions'), ('private', 'Privé - Invisible, uniquement recherche par nom')], default='public', max_length=20, verbose_name='Visibilité du profil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profil_public',
            field=models.BooleanField(default=True, verbose_name='Profil public (déprécié, utiliser profil_visibility)'),
        ),
    ]
