# Generated by Django 5.2.7 on 2025-11-17 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customuser_afficher_activite_recente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison du bannissement'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du bannissement'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL, verbose_name='Banni par'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Compte banni'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='Compte suspendu'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Suspendu jusqu'au"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison de la suspension'),
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('categorie', models.CharField(choices=[('technique', 'Problème technique'), ('question', 'Question'), ('reclamation', 'Réclamation'), ('bug', 'Bug'), ('suggestion', 'Suggestion'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('message_initial', models.TextField(verbose_name='Message initial')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20, verbose_name='Statut')),
                ('resolu_le', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_support', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Ticket support',
                'verbose_name_plural': 'Tickets support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketSupportReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_admin', models.BooleanField(default=False, verbose_name='Réponse admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réponse')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.ticketsupport', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Réponse ticket support',
                'verbose_name_plural': 'Réponses tickets support',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalementCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('spam', 'Spam'), ('harcelement', 'Harcèlement'), ('arnaque', 'Arnaque/Fraude'), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausse_information', 'Fausse information'), ('violence', 'Violence'), ('autre', 'Autre')], max_length=30, verbose_name='Raison')),
                ('description', models.TextField(blank=True, verbose_name='Description supplémentaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.postcomment', verbose_name='Commentaire signalé')),
                ('signalant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_commentaires_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Signalement de commentaire',
                'verbose_name_plural': 'Signalements de commentaires',
                'ordering': ['-created_at'],
                'unique_together': {('commentaire', 'signalant')},
            },
        ),
        migrations.CreateModel(
            name='SignalementGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('contenu_inapproprie', 'Contenu inapproprié'), ('spam', 'Spam'), ('arnaque', 'Arnaque/Fraude'), ('hate_speech', 'Discours de haine'), ('autre', 'Autre')], max_length=30, verbose_name='Raison')),
                ('description', models.TextField(blank=True, verbose_name='Description supplémentaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.group', verbose_name='Groupe signalé')),
                ('signalant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_groupes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_groupes_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Signalement de groupe',
                'verbose_name_plural': 'Signalements de groupes',
                'ordering': ['-created_at'],
                'unique_together': {('groupe', 'signalant')},
            },
        ),
        migrations.CreateModel(
            name='SignalementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('spam', 'Spam'), ('harcelement', 'Harcèlement'), ('arnaque', 'Arnaque/Fraude'), ('contenu_inapproprie', 'Contenu inapproprié'), ('menace', 'Menace'), ('autre', 'Autre')], max_length=30, verbose_name='Raison')),
                ('description', models.TextField(blank=True, verbose_name='Description supplémentaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.message', verbose_name='Message signalé')),
                ('signalant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_messages_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Signalement de message',
                'verbose_name_plural': 'Signalements de messages',
                'ordering': ['-created_at'],
                'unique_together': {('message', 'signalant')},
            },
        ),
        migrations.CreateModel(
            name='SignalementPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('spam', 'Spam'), ('harcelement', 'Harcèlement'), ('arnaque', 'Arnaque/Fraude'), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausse_information', 'Fausse information'), ('violence', 'Violence'), ('autre', 'Autre')], max_length=30, verbose_name='Raison')),
                ('description', models.TextField(blank=True, verbose_name='Description supplémentaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.post', verbose_name='Post signalé')),
                ('signalant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_posts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_posts_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Signalement de post',
                'verbose_name_plural': 'Signalements de posts',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'signalant')},
            },
        ),
    ]
