# Generated by Django 5.2.7 on 2025-11-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_admin_models_phase11'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_fraud',
            field=models.BooleanField(default=False, verbose_name='Arnaque détectée'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_inappropriate',
            field=models.BooleanField(default=False, verbose_name='Contenu inapproprié'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_quarantined',
            field=models.BooleanField(default=False, verbose_name='En quarantaine'),
        ),
        migrations.AddField(
            model_name='message',
            name='reviewed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Révisé par admin'),
        ),
        migrations.AddField(
            model_name='message',
            name='security_score',
            field=models.IntegerField(default=0, verbose_name='Score de sécurité (0-100)'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_fraud',
            field=models.BooleanField(default=False, verbose_name='Arnaque détectée'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_inappropriate',
            field=models.BooleanField(default=False, verbose_name='Contenu inapproprié'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_quarantined',
            field=models.BooleanField(default=False, verbose_name='En quarantaine'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='Spam détecté'),
        ),
        migrations.AddField(
            model_name='post',
            name='quarantine_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison de la quarantaine'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Révisé par admin'),
        ),
        migrations.AddField(
            model_name='post',
            name='security_score',
            field=models.IntegerField(default=0, verbose_name='Score de sécurité (0-100)'),
        ),
    ]
