# Generated by Django 5.2.7 on 2025-11-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_security_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalementcommentaire',
            name='raison',
            field=models.CharField(choices=[('spam', 'Spam'), ('harcelement', 'Harcèlement'), ('arnaque', 'Arnaque/Fraude'), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausse_information', 'Fausse information'), ('violence', 'Violence'), ('usurpation', "Usurpation d'identité"), ('autre', 'Autre')], max_length=30, verbose_name='Raison'),
        ),
        migrations.AlterField(
            model_name='signalementpost',
            name='raison',
            field=models.CharField(choices=[('spam', 'Spam'), ('harcelement', 'Harcèlement'), ('arnaque', 'Arnaque/Fraude'), ('contenu_inapproprie', 'Contenu inapproprié'), ('fausse_information', 'Fausse information'), ('violence', 'Violence'), ('usurpation', "Usurpation d'identité"), ('autre', 'Autre')], max_length=30, verbose_name='Raison'),
        ),
    ]
