# Generated by Django 5.2.7 on 2025-11-17 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_signalementcommentaire_raison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message de motivation')),
                ('revenus_mensuels', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Revenus mensuels')),
                ('garant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Garant (nom et contact)')),
                ('pieces_justificatives', models.FileField(blank=True, null=True, upload_to='candidatures/pieces/%Y/%m/', verbose_name='Pièces justificatives (PDF)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reponse_proprietaire', models.TextField(blank=True, null=True, verbose_name='Réponse du propriétaire')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='core.logement', verbose_name='Logement')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['logement', 'statut'], name='core_candid_logemen_65baef_idx'), models.Index(fields=['candidat', 'statut'], name='core_candid_candida_091653_idx'), models.Index(fields=['created_at'], name='core_candid_created_44316b_idx')],
                'unique_together': {('logement', 'candidat')},
            },
        ),
    ]
