# Generated by Django 5.2.7 on 2025-11-17 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='bail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.bail', verbose_name='Bail associé'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bail'], name='core_conver_bail_id_c93225_idx'),
        ),
    ]
