# Generated by Django 5.2.7 on 2025-11-17 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_conversation_bail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Bannière de profil (image)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_banner_video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/', verbose_name='Bannière de profil (vidéo)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('news', 'Actualité'), ('guide', 'Guide'), ('offer', 'Offre'), ('discussion', 'Discussion'), ('property', 'Logement'), ('group', 'Groupe')], default='discussion', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_collaborative',
            field=models.BooleanField(default=False, verbose_name='Post collaboratif'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_posts', to='core.logement', verbose_name='Logement associé'),
        ),
        migrations.CreateModel(
            name='CommentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='comments/documents/%Y/%m/', verbose_name='Document')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Type de fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_documents', to='core.postcomment')),
            ],
            options={
                'verbose_name': 'Document de commentaire',
                'verbose_name_plural': 'Documents de commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comments/images/%Y/%m/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_images', to='core.postcomment')),
            ],
            options={
                'verbose_name': 'Image de commentaire',
                'verbose_name_plural': 'Images de commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinnedAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Lien (optionnel)')),
                ('link_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texte du lien')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Annonce épinglée',
                'verbose_name_plural': 'Annonces épinglées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', '👍'), ('🔥', '🔥'), ('❤️', '❤️'), ('😊', '😊'), ('😮', '😮'), ('😢', '😢'), ('👏', '👏')], max_length=10, verbose_name='Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réaction',
                'verbose_name_plural': 'Réactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'emoji'], name='core_postre_post_id_95f915_idx')],
                'unique_together': {('post', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenu texte')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/images/%Y/%m/', verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='stories/videos/%Y/%m/', verbose_name='Vidéo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expire à')),
                ('views_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', '-created_at'], name='core_story_author__6efd3c_idx'), models.Index(fields=['expires_at'], name='core_story_expires_9d6e6b_idx')],
            },
        ),
    ]
