# Generated by Django 5.2.7 on 2025-11-17 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customuser_profile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags (séparés par des virgules)'),
        ),
        migrations.CreateModel(
            name='GroupMeetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_start', models.DateTimeField(verbose_name='Date de début')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_live', models.BooleanField(default=False, verbose_name='En direct')),
                ('visio_link', models.URLField(blank=True, null=True, verbose_name='Lien visio')),
                ('replay_link', models.URLField(blank=True, null=True, verbose_name='Lien replay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetups', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='core.group', verbose_name='Groupe')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_meetups', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Meetup/Visio',
                'verbose_name_plural': 'Meetups/Visios',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='GroupSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('show_results_public', models.BooleanField(default=True, verbose_name='Afficher résultats publiquement')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sondages', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondages', to='core.group', verbose_name='Groupe')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sondage', to='core.post', verbose_name='Post associé')),
            ],
            options={
                'verbose_name': 'Sondage',
                'verbose_name_plural': 'Sondages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_reponses', to='core.group', verbose_name='Groupe')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reponse', to='core.post', verbose_name='Post question')),
            ],
            options={
                'verbose_name': 'Question-Réponse',
                'verbose_name_plural': 'Questions-Réponses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu de la réponse')),
                ('votes_count', models.IntegerField(default=0, verbose_name='Nombre de votes')),
                ('is_official', models.BooleanField(default=False, verbose_name='Solution officielle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_questions', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponse_question', to='core.post', verbose_name='Post réponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.questionreponse', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse à une question',
                'verbose_name_plural': 'Réponses aux questions',
                'ordering': ['-votes_count', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='best_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_question', to='core.reponsequestion', verbose_name='Meilleure réponse'),
        ),
        migrations.AddField(
            model_name='questionreponse',
            name='official_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_for_question', to='core.reponsequestion', verbose_name='Solution officielle'),
        ),
        migrations.CreateModel(
            name='SondageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name="Texte de l'option")),
                ('votes_count', models.IntegerField(default=0, verbose_name='Nombre de votes')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.groupsondage', verbose_name='Sondage')),
            ],
            options={
                'verbose_name': 'Option de sondage',
                'verbose_name_plural': 'Options de sondage',
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='SousGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du sous-groupe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(default='📁', max_length=50, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_groupes', to='core.group', verbose_name='Groupe parent')),
            ],
            options={
                'verbose_name': 'Sous-groupe',
                'verbose_name_plural': 'Sous-groupes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SondageVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.sondageoption', verbose_name='Option')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.groupsondage', verbose_name='Sondage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondage_votes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vote de sondage',
                'verbose_name_plural': 'Votes de sondage',
                'unique_together': {('sondage', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VoteReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.reponsequestion', verbose_name='Réponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_reponses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vote de réponse',
                'verbose_name_plural': 'Votes de réponses',
                'unique_together': {('reponse', 'user')},
            },
        ),
    ]
