# Generated by Django 5.2.7 on 2025-11-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_group_tags_groupmeetup_groupsondage_questionreponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Message délivré'),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Délivré à'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Message épinglé'),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Épinglé à'),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Épinglé par'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='core.documentbail', verbose_name='Document partagé'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_logement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='core.logement', verbose_name='Logement partagé'),
        ),
        migrations.CreateModel(
            name='MessageMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position dans le texte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur mentionné')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='core.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Mention dans message',
                'verbose_name_plural': 'Mentions dans messages',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['message', 'mentioned_user'], name='core_messag_message_8128b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', '👍'), ('❤️', '❤️'), ('😂', '😂'), ('😮', '😮'), ('😢', '😢'), ('🔥', '🔥'), ('👏', '👏'), ('✅', '✅')], max_length=10, verbose_name='Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.message', verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réaction de message',
                'verbose_name_plural': 'Réactions de messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message', 'emoji'], name='core_messag_message_6b98c2_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_typing', models.BooleanField(default=True, verbose_name='En train de taper')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='core.conversation', verbose_name='Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Indicateur de frappe',
                'verbose_name_plural': 'Indicateurs de frappe',
                'indexes': [models.Index(fields=['conversation', 'is_typing'], name='core_typing_convers_b7c59a_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
    ]
