# Generated by Django 5.2.7 on 2025-11-17 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_message_delivered_message_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEtatLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_checklist', models.CharField(choices=[('entree', "État des lieux d'entrée"), ('sortie', 'État des lieux de sortie')], max_length=20, verbose_name='Type')),
                ('valide_par_locataire', models.BooleanField(default=False, verbose_name='Validé par le locataire')),
                ('valide_par_proprietaire', models.BooleanField(default=False, verbose_name='Validé par le propriétaire')),
                ('date_validation_locataire', models.DateTimeField(blank=True, null=True, verbose_name='Date validation locataire')),
                ('date_validation_proprietaire', models.DateTimeField(blank=True, null=True, verbose_name='Date validation propriétaire')),
                ('commentaires_locataire', models.TextField(blank=True, null=True, verbose_name='Commentaires locataire')),
                ('commentaires_proprietaire', models.TextField(blank=True, null=True, verbose_name='Commentaires propriétaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_etat_lieux', to='core.bail', verbose_name='Bail')),
                ('photos', models.ManyToManyField(blank=True, related_name='checklists_etat_lieux', to='core.imagelogement', verbose_name='Photos')),
            ],
            options={
                'verbose_name': 'Checklist état des lieux',
                'verbose_name_plural': 'Checklists état des lieux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FichierPartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='baux/fichiers_partages/%Y/%m/', verbose_name='Fichier')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fichier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('visible_locataire', models.BooleanField(default=True, verbose_name='Visible pour le locataire')),
                ('visible_proprietaire', models.BooleanField(default=True, verbose_name='Visible pour le propriétaire')),
                ('taille_fichier', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('type_fichier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_partages', to='core.bail', verbose_name='Bail')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_partages_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Fichier partagé',
                'verbose_name_plural': 'Fichiers partagés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(max_length=100, verbose_name='Pièce')),
                ('element', models.CharField(max_length=200, verbose_name='Élément')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('etat_entree', models.CharField(blank=True, choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état'), ('a_reparer', 'À réparer')], max_length=20, null=True, verbose_name='État entrée')),
                ('etat_sortie', models.CharField(blank=True, choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état'), ('a_reparer', 'À réparer')], max_length=20, null=True, verbose_name='État sortie')),
                ('photo_entree', models.ImageField(blank=True, null=True, upload_to='baux/checklist/entree/%Y/%m/', verbose_name='Photo entrée')),
                ('photo_sortie', models.ImageField(blank=True, null=True, upload_to='baux/checklist/sortie/%Y/%m/', verbose_name='Photo sortie')),
                ('notes_locataire', models.TextField(blank=True, null=True, verbose_name='Notes locataire')),
                ('notes_proprietaire', models.TextField(blank=True, null=True, verbose_name='Notes propriétaire')),
                ('valide_par_locataire', models.BooleanField(default=False, verbose_name='Validé par locataire')),
                ('valide_par_proprietaire', models.BooleanField(default=False, verbose_name='Validé par propriétaire')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.checklistetatlieux', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Item checklist',
                'verbose_name_plural': 'Items checklist',
                'ordering': ['order', 'piece', 'element'],
            },
        ),
        migrations.CreateModel(
            name='LogAccesFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Consultation'), ('download', 'Téléchargement'), ('upload', 'Upload'), ('delete', 'Suppression')], max_length=20, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acces', to='core.fichierpartage', verbose_name='Fichier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acces_fichiers', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'accès fichier",
                'verbose_name_plural': "Logs d'accès fichiers",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RappelAutomatise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('paiement', 'Paiement de loyer'), ('echeance', 'Échéance contrat'), ('entretien', 'Entretien/Maintenance'), ('document', 'Document à signer'), ('visite', 'Visite prévue'), ('autre', 'Autre')], max_length=20, verbose_name='Type de rappel')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('envoyer_email', models.BooleanField(default=True, verbose_name='Envoyer par email')),
                ('envoyer_sms', models.BooleanField(default=False, verbose_name='Envoyer par SMS')),
                ('envoyer_push', models.BooleanField(default=True, verbose_name='Envoyer notification push')),
                ('envoyer_in_app', models.BooleanField(default=True, verbose_name='Envoyer notification in-app')),
                ('date_rappel', models.DateTimeField(verbose_name='Date du rappel')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance concernée")),
                ('envoye', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('repeter', models.BooleanField(default=False, verbose_name='Répéter')),
                ('intervalle_jours', models.IntegerField(default=0, verbose_name='Intervalle (jours)')),
                ('nombre_repetitions', models.IntegerField(default=0, verbose_name='Nombre de répétitions')),
                ('repetitions_effectuees', models.IntegerField(default=0, verbose_name='Répétitions effectuées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='core.bail', verbose_name='Bail')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Rappel automatisé',
                'verbose_name_plural': 'Rappels automatisés',
                'ordering': ['date_rappel'],
            },
        ),
        migrations.CreateModel(
            name='SignatureElectronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_locataire', models.TextField(blank=True, null=True, verbose_name='Signature locataire (base64)')),
                ('signature_proprietaire', models.TextField(blank=True, null=True, verbose_name='Signature propriétaire (base64)')),
                ('date_signature_locataire', models.DateTimeField(blank=True, null=True, verbose_name='Date signature locataire')),
                ('date_signature_proprietaire', models.DateTimeField(blank=True, null=True, verbose_name='Date signature propriétaire')),
                ('ip_locataire', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP locataire')),
                ('ip_proprietaire', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP propriétaire')),
                ('device_info_locataire', models.TextField(blank=True, null=True, verbose_name='Info device locataire')),
                ('device_info_proprietaire', models.TextField(blank=True, null=True, verbose_name='Info device propriétaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de signature'), ('signe_locataire', 'Signé par le locataire'), ('signe_proprietaire', 'Signé par le propriétaire'), ('signe_complet', 'Signé par les deux parties'), ('annule', 'Annulé')], default='en_attente', max_length=30, verbose_name='Statut')),
                ('document_signe_final', models.FileField(blank=True, null=True, upload_to='baux/signatures/%Y/%m/', verbose_name='Document signé final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.bail', verbose_name='Bail')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.documentbail', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Signature électronique',
                'verbose_name_plural': 'Signatures électroniques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé'), ('escalade', "Escaladé à l'admin")], default='nouveau', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_derniere_activite', models.DateTimeField(auto_now=True, verbose_name='Date dernière activité')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('date_escalade', models.DateTimeField(blank=True, null=True, verbose_name="Date d'escalade")),
                ('jours_sans_activite', models.IntegerField(default=0, verbose_name='Jours sans activité')),
                ('escalade_auto', models.BooleanField(default=False, verbose_name='Escaladé automatiquement')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Résolution')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.bail', verbose_name='Bail')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('demande_entretien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.demandeentretien', verbose_name="Demande d'entretien liée")),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_resolus', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'verbose_name': 'Ticket/Intervention',
                'verbose_name_plural': 'Tickets/Interventions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='baux/tickets/commentaires/%Y/%m/', verbose_name='Fichier joint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.ticketintervention', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Commentaire ticket',
                'verbose_name_plural': 'Commentaires tickets',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checklistetatlieux',
            index=models.Index(fields=['bail', 'type_checklist'], name='core_checkl_bail_id_b6fa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='fichierpartage',
            index=models.Index(fields=['bail', '-created_at'], name='core_fichie_bail_id_906b03_idx'),
        ),
        migrations.AddIndex(
            model_name='fichierpartage',
            index=models.Index(fields=['uploaded_by'], name='core_fichie_uploade_6a824d_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccesfichier',
            index=models.Index(fields=['fichier', '-created_at'], name='core_logacc_fichier_0fa839_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccesfichier',
            index=models.Index(fields=['user', '-created_at'], name='core_logacc_user_id_67b14d_idx'),
        ),
        migrations.AddIndex(
            model_name='rappelautomatise',
            index=models.Index(fields=['bail', 'date_rappel'], name='core_rappel_bail_id_287eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='rappelautomatise',
            index=models.Index(fields=['destinataire', 'envoye'], name='core_rappel_destina_f3ff0a_idx'),
        ),
        migrations.AddIndex(
            model_name='rappelautomatise',
            index=models.Index(fields=['type_rappel', 'date_rappel'], name='core_rappel_type_ra_e2e887_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureelectronique',
            index=models.Index(fields=['bail', 'statut'], name='core_signat_bail_id_1d0a15_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureelectronique',
            index=models.Index(fields=['document', 'statut'], name='core_signat_documen_c50a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketintervention',
            index=models.Index(fields=['bail', 'statut'], name='core_ticket_bail_id_280aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketintervention',
            index=models.Index(fields=['cree_par', 'statut'], name='core_ticket_cree_pa_8c4d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketintervention',
            index=models.Index(fields=['assigne_a', 'statut'], name='core_ticket_assigne_1bede1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketintervention',
            index=models.Index(fields=['priorite', 'statut'], name='core_ticket_priorit_7cc33f_idx'),
        ),
    ]
