# Generated by Django 5.2.7 on 2025-11-17 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_checklistetatlieux_fichierpartage_itemchecklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disponibilite_rdv',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('bientot_disponible', 'Bientôt disponible')], default='disponible', max_length=20, verbose_name='Disponibilité pour rendez-vous'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prochain_creneau_disponible',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prochain créneau disponible'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recherche_locataire_status',
            field=models.CharField(choices=[('active', 'Recherche active'), ('passive', 'Recherche passive'), ('none', 'Ne recherche pas')], default='none', max_length=20, verbose_name='Statut de recherche de locataire'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recherche_logement_status',
            field=models.CharField(choices=[('active', 'Recherche active'), ('passive', 'Recherche passive'), ('none', 'Ne recherche pas')], default='none', max_length=20, verbose_name='Statut de recherche de logement'),
        ),
        migrations.CreateModel(
            name='InvitationPersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_invitation', models.CharField(choices=[('connection', 'Demande de connexion'), ('group', 'Invitation à un groupe'), ('event', 'Invitation à un événement'), ('collaboration', 'Invitation à collaborer'), ('other', 'Autre')], default='connection', max_length=30, verbose_name="Type d'invitation")),
                ('message_personnalise', models.TextField(blank=True, null=True, verbose_name='Message personnalisé')),
                ('est_recommandation_groupée', models.BooleanField(default=False, verbose_name='Recommandation groupée')),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='envoyee', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repondu_at', models.DateTimeField(blank=True, null=True)),
                ('autres_recommandeurs', models.ManyToManyField(blank=True, related_name='recommandations_groupées', to=settings.AUTH_USER_MODEL, verbose_name='Autres recommandeurs')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('envoyeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Envoyeur')),
            ],
            options={
                'verbose_name': 'Invitation personnalisée',
                'verbose_name_plural': 'Invitations personnalisées',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['envoyeur', 'statut'], name='core_invita_envoyeu_a7bbf0_idx'), models.Index(fields=['destinataire', 'statut'], name='core_invita_destina_2a9ada_idx'), models.Index(fields=['type_invitation', 'statut'], name='core_invita_type_in_42a89c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuggestionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_similarite', models.FloatField(default=0.0, verbose_name='Score de similarité')),
                ('raisons', models.JSONField(default=list, verbose_name='Raisons de la suggestion')),
                ('type_suggestion', models.CharField(choices=[('proche', 'Utilisateur proche'), ('similaire', 'Profil similaire'), ('quartier', 'Spécialisé dans le même quartier'), ('interet', 'Intérêts communs'), ('reseau', 'Réseau commun')], max_length=30, verbose_name='Type de suggestion')),
                ('vue', models.BooleanField(default=False, verbose_name='Vue')),
                ('acceptee', models.BooleanField(default=False, verbose_name='Acceptée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_ia', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('utilisateur_suggere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_recues', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur suggéré')),
            ],
            options={
                'verbose_name': 'Suggestion IA',
                'verbose_name_plural': 'Suggestions IA',
                'ordering': ['-score_similarite', '-created_at'],
                'indexes': [models.Index(fields=['user', '-score_similarite'], name='core_sugges_user_id_c5f51b_idx'), models.Index(fields=['type_suggestion', '-score_similarite'], name='core_sugges_type_su_65a91a_idx')],
            },
        ),
    ]
