# Generated by Django 5.2.7 on 2025-11-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_customuser_disponibilite_rdv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-importance', '-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('social', 'Réseau social'), ('content', 'Contenu & Posts'), ('messages', 'Messages'), ('groups', 'Groupes'), ('properties', 'Logements'), ('lease', 'Gestion bail'), ('security', 'Sécurité'), ('system', 'Système')], default='system', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email envoyé'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email envoyé à'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Feedback donné à'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='feedback_not_interested',
            field=models.BooleanField(default=False, verbose_name='Pas intéressant'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='importance',
            field=models.CharField(choices=[('critical', 'Critique'), ('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=20, verbose_name='Importance'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='push_sent',
            field=models.BooleanField(default=False, verbose_name='Push envoyé'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Push envoyé à'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('connection_accepted', 'Connexion acceptée'), ('connection_request', 'Demande de connexion'), ('follow', 'Nouveau follower'), ('invitation_received', 'Invitation reçue'), ('post_liked', 'Like sur un post'), ('post_commented', 'Commentaire sur un post'), ('post_reaction', 'Réaction sur un post'), ('comment_replied', 'Réponse à un commentaire'), ('post_mentioned', 'Mention dans un post'), ('comment_mentioned', 'Mention dans un commentaire'), ('post_shared', 'Post partagé'), ('collaborative_post_joined', 'Rejoint un post collaboratif'), ('new_message', 'Nouveau message'), ('message_reaction', 'Réaction sur un message'), ('message_mentioned', 'Mention dans un message'), ('group_invitation', 'Invitation à rejoindre un groupe'), ('group_post', 'Nouveau post dans un groupe'), ('group_meetup', 'Nouveau meetup dans un groupe'), ('group_sondage', 'Nouveau sondage dans un groupe'), ('group_question_answered', 'Réponse à votre question'), ('property_updated', "Mise à jour d'un logement favori"), ('property_favorited', 'Logement ajouté aux favoris'), ('review_received', 'Avis reçu'), ('review_replied', 'Réponse à votre avis'), ('bail_payment_due', 'Paiement de loyer à venir'), ('bail_payment_received', 'Paiement de loyer reçu'), ('bail_document_signed', 'Document signé'), ('bail_maintenance_request', "Nouvelle demande d'entretien"), ('bail_ticket_created', 'Nouveau ticket créé'), ('bail_ticket_resolved', 'Ticket résolu'), ('bail_reminder', 'Rappel automatique'), ('verification_approved', 'Vérification approuvée'), ('verification_rejected', 'Vérification rejetée'), ('security', 'Alerte de sécurité'), ('login_new_device', 'Connexion depuis un nouvel appareil'), ('system', 'Notification système'), ('badge_earned', 'Badge obtenu')], default='system', max_length=50),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'category', '-created_at'], name='core_userno_user_id_327e12_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'importance', '-created_at'], name='core_userno_user_id_50b3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['feedback_not_interested'], name='core_userno_feedbac_dd8586_idx'),
        ),
    ]
