# Generated by Django 5.2.7 on 2025-11-17 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_usernotification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_social', models.BooleanField(default=True, verbose_name='Réseau social')),
                ('filter_content', models.BooleanField(default=True, verbose_name='Contenu & Posts')),
                ('filter_messages', models.BooleanField(default=True, verbose_name='Messages')),
                ('filter_groups', models.BooleanField(default=True, verbose_name='Groupes')),
                ('filter_properties', models.BooleanField(default=True, verbose_name='Logements')),
                ('filter_lease', models.BooleanField(default=True, verbose_name='Gestion bail')),
                ('filter_security', models.BooleanField(default=True, verbose_name='Sécurité')),
                ('filter_system', models.BooleanField(default=True, verbose_name='Système')),
                ('filter_critical', models.BooleanField(default=True, verbose_name='Critique')),
                ('filter_high', models.BooleanField(default=True, verbose_name='Haute')),
                ('filter_medium', models.BooleanField(default=True, verbose_name='Moyenne')),
                ('filter_low', models.BooleanField(default=False, verbose_name='Basse')),
                ('disabled_types', models.JSONField(blank=True, default=list, verbose_name='Types désactivés')),
                ('enable_push', models.BooleanField(default=True, verbose_name='Notifications push navigateur')),
                ('enable_toast', models.BooleanField(default=True, verbose_name='Notifications toast')),
                ('enable_email', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('enable_in_app', models.BooleanField(default=True, verbose_name='Notifications in-app')),
                ('email_frequency', models.CharField(choices=[('immediate', 'Immédiate'), ('hourly', 'Résumé horaire'), ('daily', 'Résumé quotidien'), ('weekly', 'Résumé hebdomadaire')], default='daily', max_length=20, verbose_name='Fréquence email')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Début heures silencieuses')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin heures silencieuses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence notification',
                'verbose_name_plural': 'Préférences notifications',
            },
        ),
    ]
