# Generated by Django 5.2.7 on 2025-11-17 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cacher_activite_reseau',
            field=models.BooleanField(default=False, verbose_name='Cacher mon activité réseau (connexions, follows)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_badges',
            field=models.BooleanField(default=False, verbose_name='Cacher mes badges et récompenses'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_commentaires',
            field=models.BooleanField(default=False, verbose_name='Cacher mes commentaires sur les posts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_groupes',
            field=models.BooleanField(default=False, verbose_name='Cacher les groupes auxquels je participe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_historique_publications',
            field=models.BooleanField(default=False, verbose_name='Cacher mon historique de publications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_logements_mais_garder_profil',
            field=models.BooleanField(default=False, verbose_name='Cacher mes logements mais garder le profil visible'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_reactions',
            field=models.BooleanField(default=False, verbose_name='Cacher mes réactions (likes, etc.)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_recommandations',
            field=models.BooleanField(default=False, verbose_name='Cacher les recommandations reçues'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_statistiques',
            field=models.BooleanField(default=False, verbose_name='Cacher mes statistiques (vues, likes, etc.)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cacher_uniquement_timeline',
            field=models.BooleanField(default=False, verbose_name="Cacher uniquement la timeline d'activité"),
        ),
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('password_change', 'Changement de mot de passe'), ('2fa_enabled', '2FA activé'), ('2fa_disabled', '2FA désactivé'), ('email_verified', 'Email vérifié'), ('phone_verified', 'Téléphone vérifié'), ('profile_update', 'Mise à jour du profil'), ('avatar_change', "Changement d'avatar"), ('cover_change', 'Changement de couverture'), ('connection_request', 'Demande de connexion envoyée'), ('connection_accepted', 'Connexion acceptée'), ('connection_rejected', 'Connexion refusée'), ('follow', 'Abonnement à un utilisateur'), ('unfollow', "Désabonnement d'un utilisateur"), ('post_created', 'Post créé'), ('post_edited', 'Post modifié'), ('post_deleted', 'Post supprimé'), ('post_liked', 'Post liké'), ('post_unliked', 'Post unliké'), ('comment_created', 'Commentaire créé'), ('comment_edited', 'Commentaire modifié'), ('comment_deleted', 'Commentaire supprimé'), ('message_sent', 'Message envoyé'), ('message_received', 'Message reçu'), ('conversation_created', 'Conversation créée'), ('group_joined', 'Groupe rejoint'), ('group_left', 'Groupe quitté'), ('group_post_created', 'Post dans un groupe créé'), ('logement_created', 'Logement créé'), ('logement_updated', 'Logement modifié'), ('logement_deleted', 'Logement supprimé'), ('logement_favorited', 'Logement ajouté aux favoris'), ('logement_unfavorited', 'Logement retiré des favoris'), ('avis_posted', 'Avis posté'), ('bail_created', 'Bail créé'), ('bail_signed', 'Bail signé'), ('payment_made', 'Paiement effectué'), ('maintenance_request', "Demande d'entretien créée"), ('ticket_created', 'Ticket créé'), ('settings_updated', 'Paramètres mis à jour'), ('privacy_updated', 'Paramètres de confidentialité mis à jour'), ('notification_settings_updated', 'Paramètres de notifications mis à jour'), ('badge_earned', 'Badge obtenu'), ('report_submitted', 'Signalement soumis'), ('account_suspended', 'Compte suspendu'), ('account_unsuspended', 'Compte réactivé')], max_length=50, verbose_name="Type d'activité")),
                ('description', models.TextField(verbose_name='Description')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('device_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Informations appareil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'activité")),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.conversation', verbose_name='Conversation liée')),
                ('related_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.group', verbose_name='Groupe lié')),
                ('related_logement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.logement', verbose_name='Logement lié')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.post', verbose_name='Post lié')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_activite', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_journa_user_id_b4c9cc_idx'), models.Index(fields=['user', 'type_activite', '-created_at'], name='core_journa_user_id_edd5ac_idx'), models.Index(fields=['type_activite', '-created_at'], name='core_journa_type_ac_96fff9_idx')],
            },
        ),
    ]
