# Generated by Django 5.2.7 on 2025-11-17 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customuser_cacher_activite_reseau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('moderation_post_approved', 'Post approuvé'), ('moderation_post_rejected', 'Post rejeté'), ('moderation_post_deleted', 'Post supprimé'), ('moderation_comment_approved', 'Commentaire approuvé'), ('moderation_comment_rejected', 'Commentaire rejeté'), ('moderation_comment_deleted', 'Commentaire supprimé'), ('moderation_message_rejected', 'Message rejeté'), ('moderation_group_approved', 'Groupe approuvé'), ('moderation_group_rejected', 'Groupe rejeté'), ('user_suspended', 'Utilisateur suspendu'), ('user_unsuspended', 'Utilisateur réactivé'), ('user_banned', 'Utilisateur banni'), ('user_unbanned', 'Utilisateur débanni'), ('user_deleted', 'Utilisateur supprimé'), ('user_badges_revoked', 'Badges révoqués'), ('verification_approved', 'Vérification approuvée'), ('verification_rejected', 'Vérification rejetée'), ('batch_ban', 'Bannissement en lot'), ('batch_suspend', 'Suspension en lot'), ('batch_delete', 'Suppression en lot'), ('batch_severity_update', 'Mise à jour sévérité en lot'), ('settings_updated', 'Paramètres mis à jour'), ('export_data', 'Export de données')], max_length=50, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('device_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Informations appareil')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Navigateur')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name="Système d'exploitation")),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Localisation')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='Suspect')),
                ('suspicious_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Raison suspecte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
            ],
            options={
                'verbose_name': 'Log admin',
                'verbose_name_plural': 'Logs admin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='device_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informations appareil'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='is_recidive',
            field=models.BooleanField(default=False, verbose_name='Récidive'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='nombre_recidives',
            field=models.IntegerField(default=0, verbose_name='Nombre de récidives'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='severite',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20, verbose_name='Sévérité'),
        ),
        migrations.AddField(
            model_name='signalementcommentaire',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='device_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informations appareil'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='is_recidive',
            field=models.BooleanField(default=False, verbose_name='Récidive'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='nombre_recidives',
            field=models.IntegerField(default=0, verbose_name='Nombre de récidives'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='severite',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20, verbose_name='Sévérité'),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='signalementpost',
            name='device_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informations appareil'),
        ),
        migrations.AddField(
            model_name='signalementpost',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='signalementpost',
            name='is_recidive',
            field=models.BooleanField(default=False, verbose_name='Récidive'),
        ),
        migrations.AddField(
            model_name='signalementpost',
            name='nombre_recidives',
            field=models.IntegerField(default=0, verbose_name='Nombre de récidives'),
        ),
        migrations.AddField(
            model_name='signalementpost',
            name='severite',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20, verbose_name='Sévérité'),
        ),
        migrations.AddField(
            model_name='signalementpost',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='signalementcommentaire',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='signalementgroupe',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='signalementmessage',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='signalementpost',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='signalementpost',
            index=models.Index(fields=['statut', '-created_at'], name='core_signal_statut_f38b81_idx'),
        ),
        migrations.AddIndex(
            model_name='signalementpost',
            index=models.Index(fields=['severite', 'statut'], name='core_signal_severit_df0525_idx'),
        ),
        migrations.AddIndex(
            model_name='signalementpost',
            index=models.Index(fields=['is_recidive', '-created_at'], name='core_signal_is_reci_5ad87c_idx'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to='core.postcomment', verbose_name='Commentaire cible'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to='core.group', verbose_name='Groupe cible'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to='core.post', verbose_name='Post cible'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['admin_user', '-created_at'], name='core_adminl_admin_u_3635f9_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['action', '-created_at'], name='core_adminl_action_4b811f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['target_user', '-created_at'], name='core_adminl_target__c22b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['is_suspicious', '-created_at'], name='core_adminl_is_susp_18ea71_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='core_adminl_ip_addr_0ba10a_idx'),
        ),
    ]
