# Generated by Django 5.2.7 on 2025-11-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_adminlog_signalementcommentaire_device_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='type_activite',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('password_change', 'Changement de mot de passe'), ('2fa_enabled', '2FA activé'), ('2fa_disabled', '2FA désactivé'), ('email_verified', 'Email vérifié'), ('phone_verified', 'Téléphone vérifié'), ('profile_update', 'Mise à jour du profil'), ('avatar_change', "Changement d'avatar"), ('cover_change', 'Changement de couverture'), ('connection_request', 'Demande de connexion envoyée'), ('connection_accepted', 'Connexion acceptée'), ('connection_rejected', 'Connexion refusée'), ('follow', 'Abonnement à un utilisateur'), ('unfollow', "Désabonnement d'un utilisateur"), ('post_created', 'Post créé'), ('post_edited', 'Post modifié'), ('post_deleted', 'Post supprimé'), ('post_liked', 'Post liké'), ('post_unliked', 'Post unliké'), ('comment_created', 'Commentaire créé'), ('comment_edited', 'Commentaire modifié'), ('comment_deleted', 'Commentaire supprimé'), ('message_sent', 'Message envoyé'), ('message_received', 'Message reçu'), ('conversation_created', 'Conversation créée'), ('group_joined', 'Groupe rejoint'), ('group_left', 'Groupe quitté'), ('group_post_created', 'Post dans un groupe créé'), ('logement_created', 'Logement créé'), ('logement_updated', 'Logement modifié'), ('logement_deleted', 'Logement supprimé'), ('logement_favorited', 'Logement ajouté aux favoris'), ('logement_unfavorited', 'Logement retiré des favoris'), ('avis_posted', 'Avis posté'), ('bail_created', 'Bail créé'), ('bail_signed', 'Bail signé'), ('payment_made', 'Paiement effectué'), ('maintenance_request', "Demande d'entretien créée"), ('ticket_created', 'Ticket créé'), ('settings_updated', 'Paramètres mis à jour'), ('privacy_updated', 'Paramètres de confidentialité mis à jour'), ('notification_settings_updated', 'Paramètres de notifications mis à jour'), ('badge_earned', 'Badge obtenu'), ('report_submitted', 'Signalement soumis'), ('account_suspended', 'Compte suspendu'), ('account_unsuspended', 'Compte réactivé'), ('account_deleted', 'Compte supprimé')], max_length=50, verbose_name="Type d'activité"),
        ),
    ]
