# Generated by Django 5.2.7 on 2025-11-18 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_businessmodelcanvas_businessplan_businessplancomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_strengths_vs_competitors', models.TextField(blank=True, null=True, verbose_name='Nos forces vs concurrents')),
                ('their_strengths_to_adopt', models.TextField(blank=True, null=True, verbose_name='Leurs forces à adopter')),
                ('market_opportunities', models.TextField(blank=True, null=True, verbose_name='Opportunités marché')),
                ('competitive_threats', models.TextField(blank=True, null=True, verbose_name='Menaces concurrentielles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitive_analyses_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Analyse SWOT Comparée',
                'verbose_name_plural': 'Analyses SWOT Comparées',
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competitors/logos/', verbose_name='Logo')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('year_founded', models.IntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('funding_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Levée de fonds (€)')),
                ('estimated_users', models.IntegerField(blank=True, null=True, verbose_name="Nombre d'utilisateurs (estimé)")),
                ('feature_search', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('partial', 'Partiel')], default='no', max_length=20, verbose_name='Recherche logements')),
                ('feature_verified_reviews', models.BooleanField(default=False, verbose_name='Avis vérifiés')),
                ('feature_social_network', models.BooleanField(default=False, verbose_name='Réseau social')),
                ('feature_lease_management', models.BooleanField(default=False, verbose_name='Gestion bail')),
                ('feature_interactive_map', models.BooleanField(default=False, verbose_name='Carte interactive')),
                ('feature_mobile_app', models.BooleanField(default=False, verbose_name='Application mobile')),
                ('custom_features', models.JSONField(blank=True, default=list, verbose_name='Autres fonctionnalités custom')),
                ('pricing_model', models.CharField(choices=[('free', 'Gratuit'), ('freemium', 'Freemium'), ('paid', 'Payant'), ('commission', 'Commission'), ('mixed', 'Mixte')], default='free', max_length=20, verbose_name='Modèle tarifaire')),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix moyen (€)')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission (%)')),
                ('design_score', models.IntegerField(blank=True, null=True, verbose_name='Note design (/10)')),
                ('mobile_friendly', models.BooleanField(default=False, verbose_name='Mobile-friendly')),
                ('speed_score', models.IntegerField(blank=True, null=True, verbose_name='Note rapidité (/10)')),
                ('social_media_score', models.IntegerField(blank=True, null=True, verbose_name='Présence réseaux sociaux (/10)')),
                ('seo_score', models.IntegerField(blank=True, null=True, verbose_name='SEO (/10)')),
                ('advertising_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type de publicité')),
                ('strengths', models.TextField(blank=True, null=True, verbose_name='Points forts')),
                ('weaknesses', models.TextField(blank=True, null=True, verbose_name='Points faibles')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes libres')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitors_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Concurrent',
                'verbose_name_plural': 'Concurrents',
                'ordering': ['order', 'name'],
            },
        ),
    ]
