# Generated by Django 5.2.7 on 2025-11-18 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_competitiveanalysis_competitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cac_current', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='CAC actuel (€)')),
                ('cac_history', models.JSONField(blank=True, default=list, verbose_name='Historique CAC')),
                ('cac_sector_benchmark', models.DecimalField(decimal_places=2, default=60.0, max_digits=10, verbose_name='Benchmark secteur (€)')),
                ('ltv_current', models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='LTV actuel (€)')),
                ('ltv_cac_ratio', models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='Ratio LTV/CAC')),
                ('churn_rate_monthly', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Taux désabonnement mensuel (%)')),
                ('churn_rate_history', models.JSONField(blank=True, default=list, verbose_name='Historique Churn')),
                ('mrr_current', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='MRR actuel (€)')),
                ('mrr_history', models.JSONField(blank=True, default=list, verbose_name='Historique MRR')),
                ('burn_rate_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Burn rate mensuel (€)')),
                ('runway_months', models.IntegerField(default=12, verbose_name='Runway (mois)')),
                ('break_even_month', models.IntegerField(blank=True, null=True, verbose_name='Mois seuil rentabilité')),
                ('break_even_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='CA nécessaire seuil (€)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'KPI Financier',
                'verbose_name_plural': 'KPIs Financiers',
            },
        ),
        migrations.CreateModel(
            name='FinancialScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pessimistic', 'Pessimiste'), ('realistic', 'Réaliste'), ('optimistic', 'Optimiste')], max_length=50, verbose_name='Nom du scénario')),
                ('revenue_growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux croissance CA (%)')),
                ('conversion_rate_tenants', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Taux conversion locataires (%)')),
                ('conversion_rate_owners', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Taux conversion propriétaires (%)')),
                ('avg_subscription_price', models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Prix moyen abonnement (€)')),
                ('cac', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Coût acquisition client (€)')),
                ('ltv', models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Lifetime Value (€)')),
                ('cost_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Multiplicateur coûts')),
                ('users_month_12', models.IntegerField(default=10000, verbose_name='Nombre utilisateurs mois 12')),
                ('projected_revenue', models.JSONField(blank=True, default=dict, verbose_name='Revenus projetés')),
                ('projected_costs', models.JSONField(blank=True, default=dict, verbose_name='Coûts projetés')),
                ('projected_result', models.JSONField(blank=True, default=dict, verbose_name='Résultat projeté')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Scénario Financier',
                'verbose_name_plural': 'Scénarios Financiers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('assets_fixed_assets', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Immobilisations')),
                ('assets_receivables', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Créances clients')),
                ('assets_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Trésorerie')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total actif')),
                ('liabilities_share_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Capital social')),
                ('liabilities_reserves', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Réserves')),
                ('liabilities_financial_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dettes financières')),
                ('liabilities_trade_payables', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dettes fournisseurs')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total passif')),
                ('balance_check', models.BooleanField(default=True, verbose_name='Équilibre vérifié (Actif = Passif)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Bilan Prévisionnel',
                'verbose_name_plural': 'Bilans Prévisionnels',
                'ordering': ['year'],
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Mois')),
                ('year', models.IntegerField(default=1, verbose_name='Année')),
                ('inflows_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventes')),
                ('inflows_funding', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Levées de fonds')),
                ('inflows_loans', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prêts')),
                ('total_inflows', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total entrées')),
                ('outflows_purchases_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Achats et charges')),
                ('outflows_investments', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Investissements')),
                ('outflows_loan_repayments', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remboursements prêts')),
                ('total_outflows', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total sorties')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde initial')),
                ('variation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Variation')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Flux de Trésorerie',
                'verbose_name_plural': 'Flux de Trésorerie',
                'ordering': ['year', 'month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FinancialProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_subscriptions_tenants', models.JSONField(blank=True, default=dict, verbose_name='Revenus abonnements locataires')),
                ('revenue_subscriptions_owners', models.JSONField(blank=True, default=dict, verbose_name='Revenus abonnements propriétaires')),
                ('revenue_subscriptions_companies', models.JSONField(blank=True, default=dict, verbose_name='Revenus abonnements entreprises')),
                ('revenue_commissions_leases', models.JSONField(blank=True, default=dict, verbose_name='Commissions locations')),
                ('revenue_additional_services', models.JSONField(blank=True, default=dict, verbose_name='Services additionnels')),
                ('total_revenue', models.JSONField(blank=True, default=dict, verbose_name='Total revenus')),
                ('variable_cost_payment_commissions', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='% commissions paiement')),
                ('variable_cost_support', models.JSONField(blank=True, default=dict, verbose_name='Coûts support client')),
                ('variable_cost_marketing', models.JSONField(blank=True, default=dict, verbose_name='Marketing variable')),
                ('total_variable_costs', models.JSONField(blank=True, default=dict, verbose_name='Total charges variables')),
                ('fixed_cost_salaries', models.JSONField(blank=True, default=dict, verbose_name='Salaires équipe')),
                ('fixed_cost_rent', models.JSONField(blank=True, default=dict, verbose_name='Loyer bureaux')),
                ('fixed_cost_infrastructure', models.JSONField(blank=True, default=dict, verbose_name='Serveurs et infrastructure')),
                ('fixed_cost_marketing', models.JSONField(blank=True, default=dict, verbose_name='Marketing fixe')),
                ('fixed_cost_insurance_legal', models.JSONField(blank=True, default=dict, verbose_name='Assurances et juridique')),
                ('fixed_cost_other', models.JSONField(blank=True, default=dict, verbose_name='Autres charges fixes')),
                ('total_fixed_costs', models.JSONField(blank=True, default=dict, verbose_name='Total charges fixes')),
                ('gross_margin', models.JSONField(blank=True, default=dict, verbose_name='Marge brute')),
                ('ebitda', models.JSONField(blank=True, default=dict, verbose_name='EBITDA')),
                ('net_result', models.JSONField(blank=True, default=dict, verbose_name='Résultat net')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_projections_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Projection Financière',
                'verbose_name_plural': 'Projections Financières',
            },
        ),
    ]
