# Generated by Django 5.2.7 on 2025-11-18 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_financialkpi_financialscenario_balancesheet_cashflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('category', models.CharField(choices=[('technical', 'Technique'), ('account', 'Compte'), ('payment', 'Paiement'), ('feature', 'Fonctionnalité'), ('other', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('content', models.TextField(verbose_name='Contenu du template')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='Variables disponibles (ex: {user_name}, {ticket_id})')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Template de réponse',
                'verbose_name_plural': 'Templates de réponse',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyClaimModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=500, verbose_name='Adresse du bien')),
                ('claim_reason', models.TextField(verbose_name='Raison de la réclamation')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='Documents fournis')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', 'En cours de vérification'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('information_required', 'Informations requises')], default='pending', max_length=20, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de révision')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Notes de révision')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Raison du refus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réclamation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('property_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_moderations', to='core.logement', verbose_name='Bien concerné')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claim_moderations', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_claim_moderations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur réclamant')),
            ],
            options={
                'verbose_name': 'Réclamation de logement (Modération)',
                'verbose_name_plural': 'Réclamations de logement (Modération)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True, verbose_name='ID Ticket')),
                ('title', models.CharField(max_length=200, verbose_name='Titre/Sujet')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('technical', 'Technique'), ('account', 'Compte'), ('payment', 'Paiement'), ('feature', 'Fonctionnalité'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Catégorie')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('last_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière réponse')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Ticket de support',
                'verbose_name_plural': 'Tickets de support',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_admin_reply', models.BooleanField(default=False, verbose_name='Réponse admin')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Pièces jointes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replies', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.supportticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Réponse ticket',
                'verbose_name_plural': 'Réponses tickets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('multiple_reports', 'Plusieurs signalements'), ('suspicious_behavior', 'Comportement suspect (patterns IA)'), ('spam_detected', 'Spam détecté'), ('fake_profile', 'Profil suspect'), ('other', 'Autre')], max_length=50, verbose_name="Type d'alerte")),
                ('reports_count', models.IntegerField(default=0, verbose_name='Nombre de signalements')),
                ('suspicious_patterns', models.JSONField(blank=True, default=list, verbose_name='Patterns suspects')),
                ('status', models.CharField(choices=[('alert', 'Alerte'), ('warning_sent', 'Avertissement envoyé'), ('suspended', 'Suspendu'), ('banned', 'Banni'), ('ignored', 'Ignoré')], default='alert', max_length=20, verbose_name='Statut')),
                ('suspension_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de suspension')),
                ('ban_reason', models.TextField(blank=True, null=True, verbose_name='Raison du bannissement')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de modération')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_users', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_status', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Utilisateur à modérer',
                'verbose_name_plural': 'Utilisateurs à modérer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Commentaire'), ('message', 'Message'), ('profile', 'Profil')], max_length=50, verbose_name='Type de contenu')),
                ('content_id', models.IntegerField(verbose_name='ID du contenu')),
                ('content_preview', models.TextField(blank=True, null=True, verbose_name='Aperçu du contenu')),
                ('content_full', models.TextField(blank=True, null=True, verbose_name='Contenu complet')),
                ('reports_count', models.IntegerField(default=1, verbose_name='Nombre de signalements')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harcèlement'), ('scam', 'Arnaque'), ('inappropriate', 'Contenu inapproprié'), ('fake', 'Faux contenu'), ('other', 'Autre')], max_length=50, verbose_name='Raison du signalement')),
                ('reason_detail', models.TextField(blank=True, null=True, verbose_name='Détails de la raison')),
                ('severity', models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=20, verbose_name='Gravité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('treated', 'Traité'), ('ignored', 'Ignoré'), ('deleted', 'Supprimé')], default='pending', max_length=20, verbose_name='Statut')),
                ('treated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('treatment_notes', models.TextField(blank=True, null=True, verbose_name='Notes de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_contents', to=settings.AUTH_USER_MODEL, verbose_name='Auteur du contenu')),
                ('reported_by', models.ManyToManyField(related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
                ('treated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Contenu signalé',
                'verbose_name_plural': 'Contenus signalés',
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
    ]
