# Generated by Django 5.2.7 on 2025-11-20 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_integrationconfig_notificationconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='messages/audio/%Y/%m/', verbose_name='Message vocal'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée audio (secondes)'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('voice', 'Appel vocal'), ('video', 'Appel vidéo')], default='voice', max_length=10, verbose_name="Type d'appel")),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Sonnerie'), ('answered', 'Répondu'), ('ended', 'Terminé'), ('missed', 'Manqué'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='initiated', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu à')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('recording', models.FileField(blank=True, null=True, upload_to='calls/recordings/%Y/%m/', verbose_name='Enregistrement')),
                ('recording_enabled', models.BooleanField(default=False, verbose_name='Enregistrement activé')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Appelant')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.conversation', verbose_name='Conversation')),
                ('participants', models.ManyToManyField(related_name='calls_participated', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Appel',
                'verbose_name_plural': 'Appels',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.call', verbose_name='Appel associé'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['conversation', 'started_at'], name='core_call_convers_99d75c_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller', 'started_at'], name='core_call_caller__c8944f_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status'], name='core_call_status_53feda_idx'),
        ),
    ]
